### ISSUE TITLE
Add power sockets to table

### ISSUE THREAD

**Issue by bergie** [c-base/ingress-table#21]
Now that we have spare slots in the splitters, we could maybe expose some regular power sockets on the sides of the table. Would help in cable management when there are people hacking with laptops around the table

cc / @ij0n

**Comment by ij0n** [comment]
I would like to exchange the switch first. Currently we are only switching one of the carrying pins, which is fine, when all the other sockets are covered and nobody can touch them.

As soon as we put out additional powersockets, we should switch the power off completly at both carrying pins with the switch. 

I think the best spot for plugs are the bottom-plate. We need to measure carefully, to neither go through the floor-lights, nor through the street-lights.

**Comment by bergie** [comment]
Side of the table would be more discoverable, though

**Comment by ij0n** [comment]
The plugs fit neither below nor above the map-supportlayer-boards
