### ISSUE TITLE
Improve startup time of NoFlo

### ISSUE THREAD

**Issue by jonnor** [c-base/ingress-table#26]
NoFlo currently takes around 2 minutes to start. This is a bit annoying when rebooting the table, and a massive pain when developing/debugging.

Primary problem is the IO bottleneck by having so many different files. Should use something like noflo-iot to build into one/two files. One could be all dependencies and another file for "the rest" (things which are frequently changed during dev/debug)

**Comment by bergie** [comment]
https://github.com/djdeath/noflo-iot is a setup that builds a single-file setup of NoFlo and dependencies for Node.js. Should help on slow SD cards quite a bit

**Comment by bergie** [comment]
Initial work on a component registry cache: https://github.com/noflo/noflo/commit/b79e51563d2a1dc0d88300724dc05b8a6d32a575

This together with https://www.npmjs.com/package/coffee-cache could make starting up really fast.

**Comment by bergie** [comment]
Cache support is now in NoFlo 0.5.12 https://github.com/noflo/noflo/blob/master/CHANGES.md#0512-april-19th-2015

**Comment by bergie** [comment]
Without component cache, getting to component listing (`noflo list .`) takes 152s on the Raspberry Pi. With `--cache` it takes 80s. With [coffee-cache](https://www.npmjs.com/package/coffee-cache) installed it goes down to 60s.

cc/ @ensonic @dj-death

**Comment by bergie** [comment]
Using a lot newer NoFlo now with component cache enabled, c-base/meta#273
