### ISSUE TITLE
Hardware PWM for street lights in Tiva

### ISSUE THREAD

**Issue by jonnor** [c-base/ingress-table#27]
Should make the changes in level less jerky, and reduce CPU consumption a huge amount

Requires microflo/microflo#70

**Comment by jonnor** [comment]
MicroFlo now using Energia, with proper definitions for the Tiva C. Should now be a small matter to implement proper PWM.
http://forum.stellarisiti.com/topic/707-using-hardware-pwm-on-tiva-launchpad/
https://www.youtube.com/watch?v=_tiHHCX_MFA

**Comment by bergie** [comment]
With 79ba4a7508415b7122c55c7fa64e11f5e0464c78 we're now using hardware PWM for the pins that are capable of it.
