### ISSUE TITLE
Connect table together with other c-base systems using MQTT

### ISSUE THREAD

**Issue by jonnor** [c-base/ingress-table#30]
Possible usecases:
- Fire an animation on Matelights when c-base is attacked
- Expose the light intensity setting of table
- _your idea here!_

Would use https://github.com/the-grid/msgflo, and be a test-case for its MQTT support in a real-life "IoT" scenario

**Comment by bergie** [comment]
We already transmit to c-beam:

![screenshot 2015-04-09 at 17 35 04](https://cloud.githubusercontent.com/assets/3346/7070361/cf093e4a-dede-11e4-8193-d8542f29a593.png)

See topics in https://github.com/c-base/ingress-table/blob/master/components/PortalToMessage.coffee#L22

**Comment by bergie** [comment]
The new graph setup is now ready for this, with two participants:

* ingress-data: fetching ingress data
* ingress-lights: controlling lights

We have systemd service files for both

![screenshot 2017-05-10 at 22 23 34](https://cloud.githubusercontent.com/assets/3346/25919560/67c2ea8e-35cf-11e7-94e9-957c4fdeed61.png)
