### ISSUE TITLE
Gamma-correct the portal lights

### ISSUE THREAD

**Issue by bergie** [c-base/ingress-table#5]
From #4 @uwekamper:

> In the matelight we use the following formula to do a gamma correction on the colours:

```
GAMMA = 2.5 // 1.0 means no gamma correction
BRIGHTNESS = 0.2 // number between 0.0 and 1.0

red_corrected = round( ((red_original / 255.0) ^ GAMMA) * BRIGHTNESS * 255 );
green_corrected = round( ((green_original / 255.0) ^ GAMMA) * BRIGHTNESS * 255 );
blue_corrected = round( ((blue_original / 255.0) ^ GAMMA) * BRIGHTNESS * 255);
```

> 2.5 is the number where the colours looked most natural to us.

We should add a component for doing gamma corrections between `StateToColor` and `PortalLights` in the graph

**Comment by uwekamper** [comment]
Official color for enlightenment is #28f428, for resistance it is: #00c2ff (from website). maybe we can use those colors, too.

**Comment by bergie** [comment]
@uwekamper yep, this should be possible now that we have full RGB available. We need to figure the "accent color" for those then as well (used as the other color to blink with when portal has been recently upgraded or is L8)

**Comment by bergie** [comment]
Color control is way better now
